### PR TITLE
Set text-overflow values in WP full screen

### PR DESCRIPTION
**Pull request by HDinger**
This commit inserted overflow-values for the headline, list elements in activities overview and user comments in activities overview.

### CODE REVIEW

**Comment by basiszwo** [comment]
this can be closed, correct?

**Comment by HDinger** [comment]
Why should it not be merged?

**Comment by timhabermaas** [comment]
@HDinger @basiszwo It's still relevant, I simply forgot about it. I'll cherry-pick it now.

**Comment by timhabermaas** [comment]
Cherry-Picked: https://github.com/timhabermaas/openproject/commit/2758e453d37f56b5e37f987e7a59468b13390734

**Pull request closed without merging**
